name: dgraph
version: 1.1.2
description: >-
  Dgraph dart client.
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  fixnum: ^1.0.0
  grpc: ^3.0.2
  mutex: ^3.0.0
  protobuf: ^2.0.0
dev_dependencies:
  test: ^1.5.1
